### ISSUE TITLE
Relative path in entrypoint

### ISSUE THREAD

**Issue by DustRaven** [lhapaipai/vite-plugin-symfony#17]
Hi,
currently I'm running into the following issue: 

my app is running under https://app.domain.com/. I have a so called app router in front of it, which is available as https://router.com. All requests done to https://router.com/<path>/ are routed to https://app.domain.com/<path>/.

I run vite build with the following vite.config.js:
```JavaScript
import { defineConfig } from "vite";
import symfonyPlugin from "vite-plugin-symfony";
import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';

export default defineConfig({
    plugins: [
        react(),
        svgr(),
        symfonyPlugin({
            publicDirectory: 'public/<path>',
            buildDirectory: './',
        }),
    ],
    build: {
        rollupOptions: {
            input: {
                app: "./assets/app_react.jsx",
            },
            output: {
                manualChunks: undefined,
            }
        },
        chunkSizeWarningLimit: 1024,
    },
...
});
```

the pentatrion_vite.yaml looks like this:
```yaml
pentatrion_vite:
  # path to the web root relative to the Symfony project root directory
  public_dir: /public

  # Base public path when served in development or production
  base: /<path>
```
Everything would work, but the generated entrypoints.js contains relative paths with a leading "/", which leads to the js being requested as https://router.com/assets/app-2c11b24b.js instead of https://router.com/<path>/assets/app-2c11b24b.js:

```json
{
  "isProd": true,
  "viteServer": false,
  "entryPoints": {
    "app": {
      "js": [
        "/assets/app-2c11b24b.js"
      ],
      "css": [
        "/assets/app_react-3e032743.css"
      ],
      "preload": [],
      "legacy": false
    }
  },
  "legacy": false
}
```

Can you give me some advice on how to fix this?
